// const countries = {
//     "am-ET": "Amharic",
//     "ar-SA": "Arabic",
//     "be-BY": "Bielarus",
//     "bem-ZM": "Bemba",
//     "bi-VU": "Bislama",
//     "bjs-BB": "Bajan",
//     "bn-IN": "Bengali",
//     "bo-CN": "Tibetan",
//     "br-FR": "Breton",
//     "bs-BA": "Bosnian",
//     "ca-ES": "Catalan",
//     "cop-EG": "Coptic",
//     "cs-CZ": "Czech",
//     "cy-GB": "Welsh",
//     "da-DK": "Danish",
//     "dz-BT": "Dzongkha",
//     "de-DE": "German",
//     "dv-MV": "Maldivian",
//     "el-GR": "Greek",
//     "en-GB": "English",
//     "es-ES": "Spanish",
//     "et-EE": "Estonian",
//     "eu-ES": "Basque",
//     "fa-IR": "Persian",
//     "fi-FI": "Finnish",
//     "fn-FNG": "Fanagalo",
//     "fo-FO": "Faroese",
//     "fr-FR": "French",
//     "gl-ES": "Galician",
//     "gu-IN": "Gujarati",
//     "ha-NE": "Hausa",
//     "he-IL": "Hebrew",
//     "hi-IN": "Hindi",
//     "hr-HR": "Croatian",
//     "hu-HU": "Hungarian",
//     "id-ID": "Indonesian",
//     "is-IS": "Icelandic",
//     "it-IT": "Italian",
//     "ja-JP": "Japanese",
//     "kk-KZ": "Kazakh",
//     "km-KM": "Khmer",
//     "kn-IN": "Kannada",
//     "ko-KR": "Korean",
//     "ku-TR": "Kurdish",
//     "ky-KG": "Kyrgyz",
//     "la-VA": "Latin",
//     "lo-LA": "Lao",
//     "lv-LV": "Latvian",
//     "men-SL": "Mende",
//     "mg-MG": "Malagasy",
//     "mi-NZ": "Maori",
//     "ms-MY": "Malay",
//     "mt-MT": "Maltese",
//     "my-MM": "Burmese",
//     "ne-NP": "Nepali",
//     "niu-NU": "Niuean",
//     "nl-NL": "Dutch",
//     "no-NO": "Norwegian",
//     "ny-MW": "Nyanja",
//     "ur-PK": "Pakistani",
//     "pau-PW": "Palauan",
//     "pa-IN": "Panjabi",
//     "ps-PK": "Pashto",
//     "pis-SB": "Pijin",
//     "pl-PL": "Polish",
//     "pt-PT": "Portuguese",
//     "rn-BI": "Kirundi",
//     "ro-RO": "Romanian",
//     "ru-RU": "Russian",
//     "sg-CF": "Sango",
//     "si-LK": "Sinhala",
//     "sk-SK": "Slovak",
//     "sm-WS": "Samoan",
//     "sn-ZW": "Shona",
//     "so-SO": "Somali",
//     "sq-AL": "Albanian",
//     "sr-RS": "Serbian",
//     "sv-SE": "Swedish",
//     "sw-SZ": "Swahili",
//     "ta-LK": "Tamil",
//     "te-IN": "Telugu",
//     "tet-TL": "Tetum",
//     "tg-TJ": "Tajik",
//     "th-TH": "Thai",
//     "ti-TI": "Tigrinya",
//     "tk-TM": "Turkmen",
//     "tl-PH": "Tagalog",
//     "tn-BW": "Tswana",
//     "to-TO": "Tongan",
//     "tr-TR": "Turkish",
//     "uk-UA": "Ukrainian",
//     "uz-UZ": "Uzbek",
//     "vi-VN": "Vietnamese",
//     "wo-SN": "Wolof",
//     "xh-ZA": "Xhosa",
//     "yi-YD": "Yiddish",
//     "zu-ZA": "Zulu"
// }

const countries = {
    "am": "Amharic",
    "ar": "Arabic",
    "be": "Bielarus",
    "bem": "Bemba",
    "bi": "Bislama",
    "bjs": "Bajan",
    "bn": "Bengali",
    "bo": "Tibetan",
    "br": "Breton",
    "bs": "Bosnian",
    "ca": "Catalan",
    "cop": "Coptic",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "dz": "Dzongkha",
    "de": "German",
    "dv": "Maldivian",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fn": "Fanagalo",
    "fo": "Faroese",
    "fr": "French",
    "gl": "Galician",
    "gu": "Gujarati",
    "ha": "Hausa",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "ku": "Kurdish",
    "ky": "Kyrgyz",
    "la": "Latin",
    "lo": "Lao",
    "lv": "Latvian",
    "men": "Mende",
    "mg": "Malagasy",
    "mi": "Maori",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Burmese",
    "ne": "Nepali",
    "niu": "Niuean",
    "nl": "Dutch",
    "no": "Norwegian",
    "ny": "Nyanja",
    "ur": "Pakistani",
    "pau": "Palauan",
    "pa": "Panjabi",
    "ps": "Pashto",
    "pis": "Pijin",
    "pl": "Polish",
    "pt": "Portuguese",
    "rn": "Kirundi",
    "ro": "Romanian",
    "ru": "Russian",
    "sg": "Sango",
    "si": "Sinhala",
    "sk": "Slovak",
    "sm": "Samoan",
    "sn": "Shona",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tet": "Tetum",
    "tg": "Tajik",
    "th": "Thai",
    "ti": "Tigrinya",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tn": "Tswana",
    "to": "Tongan",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Yiddish",
    "zu": "Zulu"
  };
  